### ISSUE TITLE
为啥执行npx react-native run-android 会报这个错误

### ISSUE THREAD

**Issue by chenguotao123** [shooterRao/react-native-fruitStore#14]
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-gesture-handler:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s
25 actionable tasks: 1 executed, 24 up-to-date
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/getting-started.html

**Comment by shooterRao** [comment]
@chenguotao123 不建议用 npx 跑，npx 默认安装最新的工具链(react-native)，最新的工具跑这套环境不一定能跑得起来，建议在项目内安装依赖，即 yarn 之后再重新跑
