### ISSUE TITLE
missing s3.png?

### ISSUE THREAD

**Issue by zenghaojim33** [shooterRao/react-native-fruitStore#2]
似乎在img文件夹下缺少了几个图像

**Comment by shooterRao** [comment]
图像是齐全的，建议您重新clone下来测试看看

**Comment by yaowen2011** [comment]
src/scene/Home/Themeview.js   ../../img/s3.png  图像文件不能resolve
 很难受

**Comment by yaowen2011** [comment]
不过 微信那个项目有s开头的png图片  我拷贝过来试试

**Comment by shooterRao** [comment]
@yaowen2011 好的，确实是确了几个图像文件，谢谢指出
