### ISSUE TITLE
Bug: application eslintApp has not been registered

### ISSUE THREAD

**Issue by shuiRong** [shooterRao/react-native-fruitStore#4]
下载运行报这个错，发现`app.json`中的`name`对不上，改成`eslintApp`即可

**Comment by shooterRao** [comment]
@shuiRong 你好，这个版本我的确是在eslintApp初始化项目中开发，写完再进行转移的，转移时我已经把ios和android配置中改了，我的电脑上重装也没发现这种情况。造成这种情况的原因可能是漏了一些配置没改，请问报这种错误是在哪个平台下的？(iso or Android)还是说两个平台都存在？

**Comment by shuiRong** [comment]
> @shuiRong 你好，这个版本我的确是在eslintApp初始化项目中开发，写完再进行转移的，转移时我已经把ios和android配置中改了，我的电脑上重装也没发现这种情况。造成这种情况的原因可能是漏了一些配置没改，请问报这种错误是在哪个平台下的？(iso or Android)还是说两个平台都存在？

Android（iOS没测试）

**Comment by shooterRao** [comment]
> > @shuiRong 你好，这个版本我的确是在eslintApp初始化项目中开发，写完再进行转移的，转移时我已经把ios和android配置中改了，我的电脑上重装也没发现这种情况。造成这种情况的原因可能是漏了一些配置没改，请问报这种错误是在哪个平台下的？(iso or Android)还是说两个平台都存在？
> 
> Android（iOS没测试）

好的，我抽空看看
