### ISSUE TITLE
添加购物车有BUG

### ISSUE THREAD

**Issue by 1269372093** [shooterRao/react-native-fruitStore#7]
1.当选完商品至购物车  不点购物车图标  直接返回  从底部导航进的话  新添加的商品显示不了   但是再从购物车图标那个入口进是可以看到的。
2.新添加一个商品    然后再添加商品   要把第一个商品删除  才可以显示后面添加的商品
3.全选报错

**Comment by shooterRao** [comment]
@1269372093 你好！非常感谢测试并提出bug！上述问题均已修复 [详情](https://github.com/shooterRao/react-native-fruitStore/commit/c3e26146c7f8e5603e1197be09e17e0a36fb61a1)
